#include "TXMLEngine.h"
void xmlnewfile(const char* filename = "example.xml")
{
  // First create engine
  TXMLEngine* xml = new TXMLEngine;
  // Create main node of document tree
  XMLNodePointer_t dqid = xml->NewChild(0, 0, "DQID");
  xml->NewAttr(dqid, 0, "id","LZDQ_Miniproduction_222");
  XMLNodePointer_t subdet = xml->NewChild(dqid, 0, "SUBDET");
  xml->NewAttr(subdet, 0, "id","TPCHG");
  XMLNodePointer_t par = xml->NewChild(subdet, 0, "PAR");
  xml->NewAttr(par, 0, "id","pulseArea_phd");
  xml->NewAttr(par, 0, "flag","Green");
  XMLNodePointer_t alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","MEAN");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","StD");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  par = xml->NewChild(subdet, 0, "PAR");
  xml->NewAttr(par, 0, "id","peakTime_ns");
  xml->NewAttr(par, 0, "flag","Yellow");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","MEAN");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","StD");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Yellow");


  subdet = xml->NewChild(dqid, 0, "SUBDET");
  xml->NewAttr(subdet, 0, "id","TPCLG");
  par = xml->NewChild(subdet, 0, "PAR");
  xml->NewAttr(par, 0, "id","pulseArea_phd");
  xml->NewAttr(par, 0, "flag","Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","MEAN");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","StD");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  par = xml->NewChild(subdet, 0, "PAR");
  xml->NewAttr(par, 0, "id","peakTime_ns");
  xml->NewAttr(par, 0, "flag","Yellow");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","MEAN");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","StD");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Yellow");

  subdet = xml->NewChild(dqid, 0, "SUBDET");
  xml->NewAttr(subdet, 0, "id","Skin");
  par = xml->NewChild(subdet, 0, "PAR");
  xml->NewAttr(par, 0, "id","pulseArea_phd");
  xml->NewAttr(par, 0, "flag","Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","MEAN");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","StD");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  par = xml->NewChild(subdet, 0, "PAR");
  xml->NewAttr(par, 0, "id","peakTime_ns");
  xml->NewAttr(par, 0, "flag","Yellow");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","MEAN");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","StD");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Yellow");


  subdet = xml->NewChild(dqid, 0, "SUBDET");
  xml->NewAttr(subdet, 0, "id","ODHG");
  par = xml->NewChild(subdet, 0, "PAR");
  xml->NewAttr(par, 0, "id","pulseArea_phd");
  xml->NewAttr(par, 0, "flag","Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","MEAN");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","StD");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  par = xml->NewChild(subdet, 0, "PAR");
  xml->NewAttr(par, 0, "id","peakTime_ns");
  xml->NewAttr(par, 0, "flag","Yellow");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","MEAN");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","StD");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Yellow");


  subdet = xml->NewChild(dqid, 0, "SUBDET");
  xml->NewAttr(subdet, 0, "id","ODLG");
  par = xml->NewChild(subdet, 0, "PAR");
  xml->NewAttr(par, 0, "id","pulseArea_phd");
  xml->NewAttr(par, 0, "flag","Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","MEAN");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","StD");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  par = xml->NewChild(subdet, 0, "PAR");
  xml->NewAttr(par, 0, "id","peakTime_ns");
  xml->NewAttr(par, 0, "flag","Yellow");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","MEAN");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Green");
  alg = xml->NewChild(par, 0, "ALG");
  xml->NewAttr(alg, 0, "name","StD");
  xml->NewChild(alg, 0, "VALUE", "87.48");
  xml->NewChild(alg, 0, "LOW2", "80");
  xml->NewChild(alg, 0, "LOW", "85");
  xml->NewChild(alg, 0, "HIGH", "88");
  xml->NewChild(alg, 0, "HIGH2", "90");
  xml->NewChild(alg, 0, "FLAG", "Yellow");


  XMLDocPointer_t xmldoc = xml->NewDoc();
  xml->DocSetRootElement(xmldoc, dqid);
  // Save document to file
  xml->SaveDoc(xmldoc, filename);
  // Release memory before exit
  xml->FreeDoc(xmldoc);
  delete xml;
}
